name: highscore_functions

on:
  push:
    branches: [master]
    paths:
      - highscore-api/**
      - .github/workflows/highscore_functions.yml
  pull_request:
    branches: [master]
    paths:
      - highscore-api/**
      - .github/workflows/highscore_functions.yml

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Spin up DB
        run: |
          docker-compose up -d db
          printf 'wait for entrypoint script to run...\n' && sleep 5s
          docker-compose logs
      - name: Run dotnet build
        run: |
          cd highscore-api/HighScoreApi
          dotnet build
        env:
          CONNECTION_STRING: "Server=tcp:localhost;Database=snake-hs;User ID=sa;Password=Secret_01"
      - name: Run dotnet test
        run: |
          cd highscore-api/HighScoreApi.Tests
          dotnet test
  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Spin up DB
        run: |
          docker-compose up -d db
          printf 'wait for entrypoint script to run...\n' && sleep 5s
          docker-compose logs
      - name: Run dotnet build
        run: |
          cd highscore-api/HighScoreApi
          dotnet build --configuration Release --output ./output
        env:
          CONNECTION_STRING: "Server=tcp:localhost;Database=snake-hs;User ID=sa;Password=Secret_01"
      - name: Run dotnet test
        run: |
          cd highscore-api/HighScoreApi.Tests
          dotnet test
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/functions-action@v1
        with:
          app-name: visnakehighscores
          package: highscore-api/HighScoreApi/output
